version : '3'
services:
    ibearyouapi:
      container_name: ibearyouapi
      build: .
      volumes:
        - .:/usr/app
        - /usr/app/node_modules
      command: yarn start
      restart: always
      ports:
        - 3000:3000
      depends_on:
        - ibearyoudb
      environment:
        DATABASE_URL: postgresql://ibearyou:ibearyou@ibearyoudb:5432/ibearyou_db
    ibearyoudb :
      container_name: ibearyoudb
      image: postgres:14.0-alpine
      environment :
        - POSTGRES_DB=ibearyou_db
        - POSTGRES_USER=ibearyou
        - POSTGRES_PASSWORD=ibearyou
      restart: always
      ports:
        - "5999:5432"
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
 
networks:
  default:
    external:
      name: nginx-proxy

